### ISSUE TITLE
Error al arrancar la app desde Docker Compose

### ISSUE THREAD

**Issue by oxcar** [CodeandoMexico/decidim-monterrey#92]
![Screen Shot 2022-03-09 at 17 26 49](https://user-images.githubusercontent.com/2067516/157556382-b60f1dce-0cb8-4e2f-b7a9-7bb4d629fdb7.png)

**Comment by oxcar** [comment]
```
oscaralvarezhernandez@decidim-vm:~/decidim-monterrey$ docker-compose run decidim rails db:drop
Creating network "decidim-monterrey_default" with the default driver
Creating decidim-monterrey_decidim_run ... done
DeprecatedDSL will be removed from GraphQL-Ruby 2.0, use `.to_non_null_type` instead of `!` and remove `.activate` from /usr/local/bundle/gems/decidim-core-0.25.2/lib/decidim/core/engine.rb:89:in `block in <class:Engine>'
W, [2022-03-09T23:17:05.687913 #8]  WARN -- : Creating scope :with_attached_avatar. Overwriting existing method Decidim::User.with_attached_avatar.
W, [2022-03-09T23:17:06.034365 #8]  WARN -- : Creating scope :with_attached_avatar. Overwriting existing method Decidim::UserGroup.with_attached_avatar.
bundler: failed to load command: bin/delayed_job (bin/delayed_job)
Traceback (most recent call last):
        43: from /usr/local/bundle/bin/bundle:23:in `<main>'
        42: from /usr/local/bundle/bin/bundle:23:in `load'
        41: from /usr/local/bundle/gems/bundler-2.3.8/exe/bundle:36:in `<top (required)>'
        40: from /usr/local/bundle/gems/bundler-2.3.8/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        39: from /usr/local/bundle/gems/bundler-2.3.8/exe/bundle:48:in `block in <top (required)>'
        38: from /usr/local/bundle/gems/bundler-2.3.8/lib/bundler/cli.rb:25:in `start'
        37: from /usr/local/bundle/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        36: from /usr/local/bundle/gems/bundler-2.3.8/lib/bundler/cli.rb:31:in `dispatch'
        35: from /usr/local/bundle/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        34: from /usr/local/bundle/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        33: from /usr/local/bundle/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        32: from /usr/local/bundle/gems/bundler-2.3.8/lib/bundler/cli.rb:484:in `exec'
        31: from /usr/local/bundle/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:23:in `run'
        30: from /usr/local/bundle/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:58:in `kernel_load'
        29: from /usr/local/bundle/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:58:in `load'
        28: from bin/delayed_job:3:in `<top (required)>'
        27: from bin/delayed_job:3:in `require'
        26: from /decidim/config/environment.rb:5:in `<top (required)>'
        25: from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/application.rb:363:in `initialize!'
        24: from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/initializable.rb:60:in `run_initializers'
        23: from /usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
        22: from /usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
        21: from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
        20: from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call'
        19: from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each'
        18: from /usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
        17: from /usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
        16: from /usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        15: from /usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
        14: from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
        13: from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/initializable.rb:32:in `run'
        12: from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/initializable.rb:32:in `instance_exec'
        11: from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/application/finisher.rb:122:in `block in <module:Finisher>'
        10: from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `eager_load_all'
         9: from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `each'
         8: from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `eager_load'
         7: from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `synchronize'
         6: from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:227:in `block in eager_load'
         5: from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `ls'
         4: from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
         3: from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
         2: from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:232:in `block (2 levels) in eager_load'
         1: from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `cget'
/usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `const_get': uninitialized constant Workflows::Monterrey (NameError)
ERROR: 1
```
